// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registration.Db;

#nullable disable

namespace Registration.Db.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    [Migration("20250307090153_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Registration.Db.Model.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Registration.Db.Model.SocialMediaAddress", b =>
                {
                    b.Property<int>("RegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegistrationId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("SocialMediaAddresses");
                });

            modelBuilder.Entity("Registration.Db.Model.SocialMediaPlatform", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationRegex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SocialMediaPlatforms");
                });

            modelBuilder.Entity("Registration.Db.Model.SocialSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("SocialSkills");
                });

            modelBuilder.Entity("Registration.Db.Model.SocialMediaAddress", b =>
                {
                    b.HasOne("Registration.Db.Model.SocialMediaPlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Registration.Db.Model.Registration", null)
                        .WithMany("SocialMediaAddresses")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Registration.Db.Model.SocialSkill", b =>
                {
                    b.HasOne("Registration.Db.Model.Registration", null)
                        .WithMany("SocialSkills")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Registration.Db.Model.Registration", b =>
                {
                    b.Navigation("SocialMediaAddresses");

                    b.Navigation("SocialSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
